### ISSUE TITLE
Noise gate affecting other instances

### ISSUE THREAD

**Issue by Gimmeapill** [brummer10/guitarix.vst#5]
Another issue (also tested in Bitwig): 
if you add three instances in three tracks, load some presets (not containing the JCM800) save and reopen, the sound is very faint or fades to silence until another preset is opened.
The behavior is not exactly the same each time but problems seem to happen quite reliably.
I found nothing in the Bitwig logs.

**Comment by brummer10** [comment]
Do you've the latest checkout? 
There was a issue with engine initialisation (found it mainly in carla) were the rack was upset before the engine was inited -> crash. That's why I've had implemented a guard to avoid that, leads to a un-inited rack, but as soon you add/remove a module in the rack it was inited. Just now I've implemented a rack init call witch is called after engine is inited and before samples to process arrive. Maybe it's this bug which you describe, so, does a fresh checkout  solved that?

Nice to know that it works in Bitwig at all :)

**Comment by Gimmeapill** [comment]
That was a build from the morning, but I have just rebuilt and the issue is still there.
Ok, I found more: this is related to the noise gate I have activated on the third instance. 
If track 1 & 2 are playing something and track 2 stops, then track 1 will fade to silence. If I disable the noise gate of instance #3, the sound is back.

**Comment by brummer10** [comment]
Nice Catch. Will fix it as soon l'm Back Home. Be back in 14 days. Please continue reporting issus as you found them,

**Comment by brummer10** [comment]
So, I'm back on my developer machine and rewrite the NoiseGate. It should be fixed now in latest revision.

**Comment by Gimmeapill** [comment]
ok, I'm travelling until next week end, will test and confirm back as soon as I get back

**Comment by Gimmeapill** [comment]
Confirmed to be fixed - thanks!
